name = "email-attachment-handler"
main = "src/email-attachment-handler.js"
compatibility_date = "2023-03-16"


[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "librosphere"         # 请替换为您实际创建的R2存储桶名称
preview_bucket_name = "librosphere" # 请替换为您实际创建的R2存储桶名称


# [[analytics_engine_datasets]]
# binding = "DMARC_ANALYTICS"
# dataset = "dmarc_reports"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



